app:
    resource: "@AppBundle/Controller/"
    type:     annotation
homepage:
    path: /
    defaults:
        _controller: AppBundle\Consumer:Main:homepage

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"